# This is a basic workflow to help you get started with Actions

name: Automated Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install luarocks & vert
        timeout-minutes: 5
        run: |
          sudo apt-get install -y luarocks
          git clone https://github.com/fcr--/vert.git
          cd vert; luarocks --local make; cd ..

      - name: Test with luajit
        timeout-minutes: 5
        run: |
          echo ::group::Initialize venv-luajit
          ~/.luarocks/bin/vert init --lua-source=luajit venv-luajit
          echo ::endgroup::
          . venv-luajit/bin/activate; luajit test/tests.lua; deactivate

      - name: Test with lua5.3
        timeout-minutes: 5
        run: |
          echo ::group::Initialize venv-lua5.3
          ~/.luarocks/bin/vert init --lua-version=5.3.6 venv-lua5.3
          echo ::endgroup::
          . venv-lua5.3/bin/activate; lua test/tests.lua; deactivate

      - name: Check teal declaration files
        timeout-minutes: 1
        run: |
          luarocks --local install tl
          ~/.luarocks/bin/tl check `find -name '*.tl'`
